version: "3.7"

services:
  dashboard:
    image: dashboard_gabinete:latest
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"

    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3000/api/ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

    environment:
      - DATABASE_URL=postgresql://postgres:3cmKimOvh7U9QVTbJftX6HTVTq@postgres_postgres:5432/dashboard-apolonio
      - DASH_ADMINS=["Dani","Alipio","Ledenir","JoaoAndrade","Reimont","Divino"]
      - DASH_RESPONSAVEL_MAP={"Mita":"Mitã"}
      - DASH_USERS={"Dani":"malulu","Alipio":"apolonio2026","Ledenir":"ledenir2026","JoaoAndrade":"apopoDev","Reimont":"reimont2026","Divino":"divino2026","Janaina":"janaina2026","Mita":"mita2026","Suellyema":"suellyema2026","Natalia":"natalia2026","Claudina":"claudina2026","Carin":"carin2026","Rayana":"rayana2026"}}
      - JWT_SECRET=DZ5xWCyOCIFabkXJH72ybdqZsV
      - REDIS_URL=redis://redis_redis:6379
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - NODE_ENV=production

    networks:
      - ApolonioNet

    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard-gabinete.rule=Host(`dashboard.gabinete.cloud`)"
        - "traefik.http.routers.dashboard-gabinete.entrypoints=websecure"
        - "traefik.http.routers.dashboard-gabinete.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.dashboard-gabinete.loadbalancer.server.port=3000"
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 512M

networks:
  ApolonioNet:
    external: true
    name: ApolonioNet
